
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.101.157.241:3306/test_unistrong_dev?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000Mb
      max-request-size: 100000Mb
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.attackme.myuploader.model
upload:
  windPath: E:\upload\
  linuxPath: /data/fota/files/
  url: http://192.168.108.87/fota/files/
  #url: http://helloki.top/fota/files/
server:
  port: 8085


---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.108.87:3306/test_unistrong_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
upload:
  windPath: E:\upload\
  linuxPath: /data/fota/files/
  url: http://192.168.12.61/fota/files/
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.12.61:3306/unistrong_fota?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
upload:
  windPath: E:\upload\
  linuxPath: /data/fota/files/
  url: http://192.168.12.61/fota/files/